version: "3.8"
services:
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/barry/mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped